services:
  db:
    image: mysql:8.0
    container_name: todolist-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: todolist
      MYSQL_USER: devops
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8081:80"
    container_name: todolist-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: todolist
      DB_USER: devops
      DB_PASS: securepassword
    restart: unless-stopped

  frontend:
    build: ./frontend
      ports:
      - "8888:80"          
    container_name: todolist-frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: